language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  local-dir: dist
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master